/**
 * TrendSmart QA — Bug Report Generator
 *
 * Takes raw bug reports from all agents and produces:
 *  1. GitHub-issue-ready markdown files (one per bug)
 *  2. A summary dashboard (markdown)
 *  3. A CSV for spreadsheet triage
 *  4. Deduplication & confidence scoring
 *
 * This is what a QA lead would produce after a test cycle.
 */

import type { BugReport, QAReport, BugSeverity } from "./agent-types";
import * as fs from "fs";
import * as path from "path";

const OUTPUT_DIR = path.join(process.cwd(), "docs", "gui-audit");

function ensureDir(dir: string): void {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

// ── Deduplication ─────────────────────────────────────────────────

/**
 * Deduplicate bugs by merging similar findings from different agents.
 * Two bugs are "similar" if they affect the same route and have
 * overlapping keywords in their title.
 */
export function deduplicateBugs(bugs: BugReport[]): BugReport[] {
  const seen = new Map<string, BugReport>();

  for (const bug of bugs) {
    // Build a dedup key: route + normalized title words
    const keyWords = bug.title
      .toLowerCase()
      .replace(/[^a-z0-9\s]/g, "")
      .split(/\s+/)
      .filter((w) => w.length > 3)
      .sort()
      .join("|");
    const key = `${bug.route}::${keyWords}`;

    if (seen.has(key)) {
      const existing = seen.get(key)!;
      // Keep the one with higher confidence
      if (bug.confidence > existing.confidence) {
        seen.set(key, {
          ...bug,
          labels: [...new Set([...existing.labels, ...bug.labels])],
        });
      }
    } else {
      seen.set(key, bug);
    }
  }

  return Array.from(seen.values());
}

// ── GitHub Issue Markdown ─────────────────────────────────────────

/**
 * Format a single bug as a GitHub-issue-ready markdown file.
 */
function bugToGitHubIssue(bug: BugReport): string {
  const severityEmoji: Record<BugSeverity, string> = {
    critical: "P0-critical",
    major: "P1-major",
    minor: "P2-minor",
    cosmetic: "P3-cosmetic",
  };

  return [
    `# ${bug.title}`,
    ``,
    `**Labels:** ${bug.labels.map((l) => `\`${l}\``).join(", ")}`,
    `**Priority:** ${severityEmoji[bug.severity]}`,
    `**Confidence:** ${bug.confidence}%`,
    `**Found by:** ${bug.foundBy} agent`,
    `**Route:** \`${bug.route}\``,
    bug.relatedFile ? `**Related file:** \`${bug.relatedFile}\`` : "",
    ``,
    `## Steps to Reproduce`,
    ...bug.stepsToReproduce.map((s, i) => `${i + 1}. ${s}`),
    ``,
    `## Expected Behavior`,
    bug.expected,
    ``,
    `## Actual Behavior`,
    bug.actual,
    ``,
    `## Suggested Fix`,
    bug.suggestedFix,
    bug.screenshotPath ? `\n## Screenshot\n![screenshot](${bug.screenshotPath})` : "",
    ``,
    `---`,
    `*Generated by TrendSmart QA Bot*`,
  ]
    .filter(Boolean)
    .join("\n");
}

// ── Summary Dashboard ─────────────────────────────────────────────

/**
 * Generate a markdown summary of all findings.
 */
function generateDashboard(report: QAReport): string {
  const { summary, bugs } = report;
  const lines: string[] = [];

  lines.push(`# TrendSmart QA Report`);
  lines.push(`**Generated:** ${report.meta.timestamp}`);
  lines.push(`**Duration:** ${(report.meta.duration / 1000).toFixed(1)}s`);
  lines.push(`**Agents:** ${report.meta.agents.join(", ")}`);
  lines.push(``);

  // Summary box
  lines.push(`## Summary`);
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total Bugs | **${summary.totalBugs}** |`);
  lines.push(`| Critical | ${summary.bySeverity.critical || 0} |`);
  lines.push(`| Major | ${summary.bySeverity.major || 0} |`);
  lines.push(`| Minor | ${summary.bySeverity.minor || 0} |`);
  lines.push(`| Cosmetic | ${summary.bySeverity.cosmetic || 0} |`);
  lines.push(`| API Tests Passed | ${summary.apiTestsPassed}/${summary.apiTestsPassed + summary.apiTestsFailed} |`);
  lines.push(`| Flow Tests Passed | ${summary.flowTestsPassed}/${summary.flowTestsPassed + summary.flowTestsFailed} |`);
  lines.push(`| Avg Confidence | ${summary.avgConfidence.toFixed(0)}% |`);
  if (summary.performanceScore !== undefined)
    lines.push(`| Performance Score | ${summary.performanceScore}/100 |`);
  if (summary.securityScore !== undefined)
    lines.push(`| Security Score | ${summary.securityScore}/100 |`);
  if (summary.seoScore !== undefined)
    lines.push(`| SEO Score | ${summary.seoScore}/100 |`);
  lines.push(``);

  // Trend
  if (report.trendReport) {
    const t = report.trendReport;
    const arrow = t.direction === "improving" ? "IMPROVING" : t.direction === "degrading" ? "DEGRADING" : "STABLE";
    lines.push(`## Trend: ${arrow}`);
    if (t.regressions.length > 0) {
      lines.push(`### Regressions`);
      for (const r of t.regressions) lines.push(`- ${r}`);
    }
    if (t.improvements.length > 0) {
      lines.push(`### Improvements`);
      for (const imp of t.improvements) lines.push(`- ${imp}`);
    }
    lines.push(``);
  }

  // Performance metrics
  if (report.performanceMetrics && report.performanceMetrics.length > 0) {
    lines.push(`## Performance Metrics`);
    lines.push(`| Route | LCP | FCP | CLS | TBT | DOM Nodes | Load |`);
    lines.push(`|-------|-----|-----|-----|-----|-----------|------|`);
    for (const m of report.performanceMetrics) {
      lines.push(`| \`${m.route}\` | ${m.lcp}ms | ${m.fcp}ms | ${m.cls} | ${m.tbt}ms | ${m.domNodes} | ${m.fullLoad}ms |`);
    }
    lines.push(``);
  }

  // Security results
  if (report.securityResults && report.securityResults.length > 0) {
    const secFailed = report.securityResults.filter((r) => !r.passed);
    if (secFailed.length > 0) {
      lines.push(`## Security Issues`);
      lines.push(`| Check | Target | Severity | Details |`);
      lines.push(`|-------|--------|----------|---------|`);
      for (const r of secFailed) {
        lines.push(`| ${r.check} | \`${r.target.substring(0, 40)}\` | ${r.severity} | ${r.details.substring(0, 60)} |`);
      }
      lines.push(``);
    }
  }

  // SEO summary
  if (report.seoAudits && report.seoAudits.length > 0) {
    const seoIssueCount = report.seoAudits.reduce((s, a) => s + a.issues.length, 0);
    if (seoIssueCount > 0) {
      lines.push(`## SEO Issues (${seoIssueCount} total)`);
      for (const audit of report.seoAudits) {
        if (audit.issues.length > 0) {
          lines.push(`- \`${audit.route}\`: ${audit.issues.join(", ")}`);
        }
      }
      lines.push(``);
    }
  }

  // By agent
  lines.push(`## Bugs by Agent`);
  for (const [agent, count] of Object.entries(summary.byAgent)) {
    lines.push(`- **${agent}**: ${count} bugs`);
  }
  lines.push(``);

  // By route
  lines.push(`## Bugs by Route`);
  const routeEntries = Object.entries(summary.byRoute).sort((a, b) => b[1] - a[1]);
  for (const [route, count] of routeEntries) {
    lines.push(`- \`${route}\`: ${count}`);
  }
  lines.push(``);

  // Critical bugs table
  const criticalBugs = bugs.filter((b) => b.severity === "critical");
  if (criticalBugs.length > 0) {
    lines.push(`## Critical Bugs (Needs Immediate Attention)`);
    lines.push(`| ID | Title | Route | Agent | Confidence |`);
    lines.push(`|----|-------|-------|-------|------------|`);
    for (const bug of criticalBugs) {
      lines.push(
        `| ${bug.id} | ${bug.title.substring(0, 60)} | \`${bug.route}\` | ${bug.foundBy} | ${bug.confidence}% |`
      );
    }
    lines.push(``);
  }

  // All bugs table
  lines.push(`## All Bugs`);
  lines.push(`| ID | Severity | Title | Route | Agent | Confidence |`);
  lines.push(`|----|----------|-------|-------|-------|------------|`);
  for (const bug of bugs) {
    lines.push(
      `| ${bug.id} | ${bug.severity} | ${bug.title.substring(0, 50)} | \`${bug.route}\` | ${bug.foundBy} | ${bug.confidence}% |`
    );
  }

  return lines.join("\n");
}

// ── CSV Export ─────────────────────────────────────────────────────

function generateCSV(bugs: BugReport[]): string {
  const escape = (s: string) => `"${s.replace(/"/g, '""')}"`;

  const header =
    "ID,Severity,Title,Route,Agent,Confidence,Labels,Expected,Actual,SuggestedFix,RelatedFile";

  const rows = bugs.map((b) =>
    [
      b.id,
      b.severity,
      escape(b.title),
      b.route,
      b.foundBy,
      b.confidence,
      escape(b.labels.join("; ")),
      escape(b.expected),
      escape(b.actual),
      escape(b.suggestedFix),
      b.relatedFile || "",
    ].join(",")
  );

  return [header, ...rows].join("\n");
}

// ── Main Export Function ──────────────────────────────────────────

/**
 * Save the full QA report to disk in multiple formats.
 */
export function saveQAReport(report: QAReport): {
  reportPath: string;
  dashboardPath: string;
  csvPath: string;
  issuesDir: string;
  issueCount: number;
} {
  ensureDir(OUTPUT_DIR);
  const issuesDir = path.join(OUTPUT_DIR, "issues");
  ensureDir(issuesDir);

  // 1. Full JSON report
  const reportPath = path.join(OUTPUT_DIR, "qa-report.json");
  fs.writeFileSync(reportPath, JSON.stringify(report, null, 2));

  // 2. Markdown dashboard
  const dashboardPath = path.join(OUTPUT_DIR, "qa-dashboard.md");
  fs.writeFileSync(dashboardPath, generateDashboard(report));

  // 3. CSV
  const csvPath = path.join(OUTPUT_DIR, "bugs.csv");
  fs.writeFileSync(csvPath, generateCSV(report.bugs));

  // 4. Individual GitHub issues
  for (const bug of report.bugs) {
    const filename = `${bug.id}.md`;
    fs.writeFileSync(
      path.join(issuesDir, filename),
      bugToGitHubIssue(bug)
    );
  }

  return {
    reportPath,
    dashboardPath,
    csvPath,
    issuesDir,
    issueCount: report.bugs.length,
  };
}
